### PR TITLE
Fixes issue #5

### PR DESCRIPTION
**Pull request by Alackey**
Unable to test on OSX and Windows, but it should not cause any problems as it is just another way to achieve the same goal.

### CODE REVIEW

**Comment by yask123** [comment]
Look good :+1: 

I just merged another PR, which caused some conflicts.
Can you pull the changes and re-commit your changes ?

Thanks.

**Comment by Alackey** [comment]
It's seems to be good now.

**Comment by yask123** [comment]
I just tested my current code on Ubuntu machine, and it worked ?

**Comment by Alackey** [comment]
Works fine for me. Linux Mint 17.2.

**Comment by yask123** [comment]
Nah, I meant, it works with `with open ...`

**Comment by Alackey** [comment]
I tried it with my local machine Linux Mint and a Ubuntu 14.04 Virtual machine, and I am still getting the error without the change I made.

**Comment by yask123** [comment]
Thanks! Looks good :+1:

**Pull request merged**
